### ISSUE TITLE
Unclear Error for PK Field Order

### ISSUE THREAD

**Issue by sfc-gh-abouts** [sfc-gh-pneedleman/snowflake-streamlit-table-updater#4]
Hey Paul, I used this for a customer hackathon.  It worked great once we got past an error.  For whatever reason, prolly b/c it was a hackathon, their PK field was the second field in the table.  When this happens, the updater query throws an SQL error that said there's a duplicate field.  The error is confusing and query history doesn't really show how to fix this.

The customer did a create or replace DDL to move their PK from column #2 to column #1 and then this app worked as expected.

Can you add an error if the PK isn't field #1?

Happy to discuss on Slack if you have any questions.

**Comment by sfc-gh-pneedleman** [comment]
Yes and thanks for the suggestion. Will try to get this in.

**Comment by sfc-gh-pneedleman** [comment]
@sfc-gh-abouts - I tested this and was unable to reproduce the issue. I created a test table with a PK in the second column and it worked as expected. Please let me know if you can share more details.

**Comment by sfc-gh-abouts** [comment]
Thanks @sfc-gh-pneedleman , I tested this in my demo account and I also could not repro it.  I guess it's possible that our demo accounts were ahead of the customer's version of Snowflake.  I could ask the customer to try to repro it again, but for now I think we should just close this.
